
spring.datasource.url=jdbc:postgresql://neondb_owner:npg_FNJXecGav27w@ep-plain-frog-zahgm1q6-pooler.c-2.eu-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

dni.encryption.key=${DNI_ENCRYPTION_KEY}
